name: linux

on:
  pull_request:
    branches: [ main ]

env:
  BASE_PACKAGES: binutils gcc g++ gfortran cmake python3 perl git git-lfs curl wget tar unzip build-essential

jobs:
  build_uberenv_mode:
    name: Uberenv Build Mode (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
          sudo apt-get update
          sudo apt-get install $BASE_PACKAGES
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd .ci/test-project
          python3 ../../uberenv.py --project-json=uberenv_config.json
          cat uberenv_libs/*.cmake
  build_dev_build_full_mode:
    name: Dev Build Full Mode (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
          sudo apt-get update
          sudo apt-get install $BASE_PACKAGES
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd .ci/test-project
          python3 ../../uberenv.py --project-json=dev_build_config.json --spack-config-dir=spack_configs/linux_ubuntu_20
  build_install_full_mode:
    name: Install Full Mode (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
          sudo apt-get update
          sudo apt-get install $BASE_PACKAGES
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd .ci/test-project
          python3 ../../uberenv.py --project-json=install_config.json --spack-config-dir=spack_configs/linux_ubuntu_20
  build_dev_build_initconfig_mode:
    name: Dev Build Initconfig Mode (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
          sudo apt-get update
          sudo apt-get install $BASE_PACKAGES
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd .ci/test-project
          python3 ../../uberenv.py --project-json=dev_build_config.json --spack-config-dir=spack_configs/linux_ubuntu_20 --package-final-phase=initconfig
  build_install_initconfig_mode:
    name: Install Initconfig Mode (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
          sudo apt-get update
          sudo apt-get install $BASE_PACKAGES
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd .ci/test-project
          python3 ../../uberenv.py --project-json=install_config.json --spack-config-dir=spack_configs/linux_ubuntu_20 --package-final-phase=initconfig
