name: linux

on:
  pull_request:
    branches: [ master ]

jobs:
  build_uberenv_pkg:
    name: Uberenv Pkg Mode
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd  .ci/test-project
          python ../../uberenv.py  --project-json=uberenv_config.json
          cat uberenv_libs/*.cmake
  build_env:
    name: Spack Env Mode
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential
    - uses: actions/checkout@v2
    - name: Run Uberenv
      run: |
          cd  .ci/test-project-spack-env
          python ../../uberenv.py  --spack-env=spack_configs/spack.yaml  --project-json=uberenv_config.json
          cat uberenv_libs/*.cmake


